### ISSUE TITLE
Duplicate file path being added

### ISSUE THREAD

**Issue by jameshmread** [adamdallis/ProfessorX#9]
extra "\testProject\src"
ProfessorX\testProject\src**\testProject\src**\HelloWorld.ts.spec.m.ts
Stack Trace
Error: Cannot find module 'ProfessorX\testProject\src\testProject\src\HelloWorld.ts.spec.m.ts'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at ProfessorX\node_modules\mocha\lib\mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (ProfessorX\node_modules\mocha\lib\mocha.js:227:14)
    at Mocha.run (ProfessorX\node_modules\mocha\lib\mocha.js:495:10)
    at MochaTestRunner.run (ProfessorX\src\mocha-TestRunner\Mocha-TestRunner.ts:36:29)
    at Object.<anonymous> (ProfessorX\src\index.ts:30:13)

So far it has been fixed by only adding the first, correct, file to the mocha test runner

**Comment by jameshmread** [comment]
fixed #10
